apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  selector:
    matchLabels:
      app: pyapp
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
