apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  selector:
    matchLabels:
      app: pyapp
  replicas: 1
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: smolnax/task3
        imagePullPolicy: Always
        ports:
          - containerPort: 80
